npm link ../../../ViewerApi/packages/viewer.api
npm link ../../../ViewerDataEngine/packages/viewer.data-engine.data-engine
npm link ../../../ViewerDataEngine/packages/viewer.data-engine.geometry-engine
npm link ../../../ViewerDataEngine/packages/viewer.data-engine.material-engine
npm link ../../../ViewerMonitoring/packages/viewer.monitoring.error-handler
npm link ../../../ViewerMonitoring/packages/viewer.monitoring.logger
npm link ../../../ViewerMonitoring/packages/viewer.monitoring.performance-evaluator
npm link ../../../ViewerNodeTree/packages/viewer.node-tree.tree
npm link ../../../ViewerNodeTree/packages/viewer.node-tree.tree-node
npm link ../../../ViewerNodeTree/packages/viewer.node-tree.tree-node-data
npm link ../../../ViewerSdTF/packages/viewer.sdtf.converter
npm link ../../../ViewerSdTF/packages/viewer.sdtf.parser
npm link ../../../ViewerSdTF/packages/viewer.sdtf.shared
npm link ../../../ViewerSessionEngine/packages/viewer.session-engine.session-engine
npm link ../../../ViewerShared/packages/viewer.shared.event-engine
npm link ../../../ViewerShared/packages/viewer.shared.settings-engine
npm link ../../../ViewerShared/packages/viewer.shared.types
npm link ../../../ViewerUtils/packages/viewer.utils.http-client
npm link ../../../ViewerUtils/packages/viewer.utils.image-loader
npm link ../../../ViewerUtils/packages/viewer.utils.uuid
npm link ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.camera-engine
npm link ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.canvas-engine
npm link ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.light-engine
npm link ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.rendering-engine
npm link ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.rendering-engine-babylonjs
npm link ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.rendering-engine-management
npm link ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.rendering-engine-threejs