npm i ../../../ViewerApi/packages/viewer.api --save
npm i ../../../ViewerDataEngine/packages/viewer.data-engine.data-engine --save
npm i ../../../ViewerDataEngine/packages/viewer.data-engine.geometry-engine --save
npm i ../../../ViewerDataEngine/packages/viewer.data-engine.material-engine --save
npm i ../../../ViewerMonitoring/packages/viewer.monitoring.error-handler --save
npm i ../../../ViewerMonitoring/packages/viewer.monitoring.logger --save
npm i ../../../ViewerMonitoring/packages/viewer.monitoring.performance-evaluator --save
npm i ../../../ViewerNodeTree/packages/viewer.node-tree.tree --save
npm i ../../../ViewerNodeTree/packages/viewer.node-tree.tree-node --save
npm i ../../../ViewerNodeTree/packages/viewer.node-tree.tree-node-data --save
npm i ../../../ViewerSdTF/packages/viewer.sdtf.converter --save
npm i ../../../ViewerSdTF/packages/viewer.sdtf.parser --save
npm i ../../../ViewerSdTF/packages/viewer.sdtf.shared --save
npm i ../../../ViewerSessionEngine/packages/viewer.session-engine.session-engine --save
npm i ../../../ViewerShared/packages/viewer.shared.event-engine --save
npm i ../../../ViewerShared/packages/viewer.shared.settings-engine --save
npm i ../../../ViewerShared/packages/viewer.shared.types --save
npm i ../../../ViewerUtils/packages/viewer.utils.http-client --save
npm i ../../../ViewerUtils/packages/viewer.utils.image-loader --save
npm i ../../../ViewerUtils/packages/viewer.utils.uuid --save
npm i ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.camera-engine --save
npm i ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.canvas-engine --save
npm i ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.light-engine --save
npm i ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.rendering-engine --save
npm i ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.rendering-engine-babylonjs --save
npm i ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.rendering-engine-management --save
npm i ../../../ViewerVisualizationEngine/packages/viewer.visualization-engine.rendering-engine-threejs --save